name: GalaxyEconomy
version: '${project.version}'
load: STARTUP
main: dev.joel.galaxyeconomy.GalaxyEconomy
description: atgweahbsdzedrtgjn
depend: [ Vault ]
softdepend: [ PlaceholderAPI ]
author: Atom/Joel
commands:
  money: